In [14]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.metrics.pairwise import cosine_distances

In [41]:
vec = CountVectorizer(lowercase=True)

In [51]:
docs = ["The quick brown fox jumps over the lazy dog", "Aa quick brown dog outpaces aa quick fox"]

In [52]:
data = vec.fit_transform(docs)

In [53]:
data.toarray()

array([[0, 1, 1, 1, 1, 1, 0, 1, 1, 2],
       [2, 1, 1, 1, 0, 0, 1, 0, 2, 0]])

In [54]:
euclidean_distances(data.toarray()[0], data.toarray()[1])

/Users/rituc/anaconda2/anaconda/envs/gl-env/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/rituc/anaconda2/anaconda/envs/gl-env/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[ 3.60555128]])

In [55]:
cosine_distances(data.toarray()[0], data.toarray()[1])

/Users/rituc/anaconda2/anaconda/envs/gl-env/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/rituc/anaconda2/anaconda/envs/gl-env/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[ 0.56480586]])

In [48]:
vocab = vec.vocabulary_

In [49]:
len(vocab)

10

In [50]:
vocab

{u'aa': 0,
 u'brown': 1,
 u'dog': 2,
 u'fox': 3,
 u'jumps': 4,
 u'lazy': 5,
 u'outpaces': 6,
 u'over': 7,
 u'quick': 8,
 u'the': 9}